import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'nathanbreitsch' at '4/2/16 8:29 PM' with Gradle 2.10
 *
 * @author nathanbreitsch, @date 4/2/16 8:29 PM
 */
public class PointTest {
    @Test public void testDifference() {
        Point p1 = new Point(10, 5);
        Point p2 = new Point(3, 4);
        Point difference = Point.difference(p1, p2);

        assertTrue("Point.difference gives correct x value", difference.x == 7);
        assertTrue("Point.difference gives correct y value", difference.y == 1);
    }

    @Test public void testCrossProduct(){
      Point p1 = new Point(1, 0);
      Point p2 = new Point(0, 1);

      double delta = 0.001;

      assertEquals(1.0, Point.crossProduct(p1, p2), delta);
      assertEquals(-1.0, Point.crossProduct(p2, p1), delta);
      assertEquals(0, Point.crossProduct(p1, p1), delta);
    }
}
