import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'nathanbreitsch' at '4/2/16 8:29 PM' with Gradle 2.10
 *
 * @author nathanbreitsch, @date 4/2/16 8:29 PM
 */
public class QuickHullTest {
    @Test public void testSomeLibraryMethod() {
        QuickHull classUnderTest = new QuickHull();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
